### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Trumeet** [unnamed5719/coolapk-cli#2]
不懂Python（~~PY~~，划掉），运行出错..
```
  File ".\coolapk-cli.py", line 114
    print("%.2f%%" % percentage, end="\r")
                                    ^
SyntaxError: invalid syntax
```

**Comment by unnamed5719** [comment]
请问运行环境及Python版本

**Comment by Trumeet** [comment]
@unnamed5719 2.7和3.6都不行（

**Comment by Trumeet** [comment]
@unnamed5719 Win10系统

**Comment by unnamed5719** [comment]
@Trumeet 这就奇怪了，你试试看把114行的
`print("%.2f%%" % percentage, end="\r")`
改成
`print("%.2f%%" % percentage)`
那个\r是转义的用来刷新进度，没了的话只会输出很多行，不过应该能用
BTW，2.x和3.x部分代码是不兼容的

**Comment by Trumeet** [comment]
@unnamed5719 解决了，编码问题。但是有新问题：
```
Traceback (most recent call last):
  File ".\coolapk-cli.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```
诶诶 不懂Python真可怕2333，dalao勿喷..

**Comment by BruceZhang1993** [comment]
@Trumeet 
问题1   下载进度的问题，这个 end= 语法仅支持 python3 ，有时间我写个兼容
问题2   你可以 pip install requests 

@unnamed5719 
弃用 requests 而改用自带 urllib 库如何，不过还是得做兼容(雾

**Comment by unnamed5719** [comment]
@BruceZhang1993 
end= 可以用sys.stdout.write解决吧
requests是好东西啊_(:з」∠)_，不如另外做个兼容py2，用urllib的版本？

**Comment by BruceZhang1993** [comment]
@unnamed5719 
目前只需要加个 `from __future__ import print_function as print` 即可导入兼容 py2 的 print 函数
你可以测试 可以的话提交个版本

**Comment by unnamed5719** [comment]
@BruceZhang1993 
好吧，那我去写一个用urllib的版本
只不过只有手机，可能要久一点_(:з」∠)_

**Comment by BruceZhang1993** [comment]
@unnamed5719 手机写好厉害！！

**Comment by unnamed5719** [comment]
@BruceZhang1993 
噢，我忘了，py3把urllib2给合起来了
那写个用urllib2的py2版吧...

**Comment by unnamed5719** [comment]
@BruceZhang1993 
py2版推送到新的branch了，似乎注释掉的那几行有问题，帮忙解决一下

**Comment by BruceZhang1993** [comment]
一直用的 py3 ，py2 咱也不太明白啊

**Comment by iVanilla** [comment]
正在学习~~PY~~Python无鸭梨

**Comment by unnamed5719** [comment]
推荐使用requests库，不想使用的话我已经上传一个urllib版的了，见仓库
