### ISSUE TITLE
征求：是否有必要添加app内的功能

### ISSUE THREAD

**Issue by unnamed5719** [unnamed5719/coolapk-cli#3]
目前觉得已经将网页版榨干，希望获取更多有用的api
可是酷安对客户端的api进行了请求验证，见[酷安开源版](https://github.com/bjzhou/Coolapk)
我还是Python新手，不知道如何调用库文件
如果此功能实现，可以更好地实现市场功能
如更详细的应用信息及检查更新等
Waiting for your response.

**Comment by BruceZhang1993** [comment]
Python 可以 ctypes 调用C/C++动态库文件 但酷安动态库是 ARM 架构 意味着无法在电脑终端上成功运行

**Comment by unnamed5719** [comment]
@BruceZhang1993 查看安装包发现也有x86架构的so文件

**Comment by BruceZhang1993** [comment]
@unnamed5719 
只用了这行代码拿个Token而已 很简单  https://github.com/bjzhou/Coolapk/blob/master/app/src/main/kotlin/bjzhou/coolapk/app/net/ApiManager.kt#L54
方便提取个 x86 的 so 给测试一下么

**Comment by unnamed5719** [comment]
拆酷安的包就行了呀 @BruceZhang1993

**Comment by BruceZhang1993** [comment]
@unnamed5719 
OSError: ./liba.so: wrong ELF class: ELFCLASS32
我想咱需求一个 64 位库或者去 32 位环境测试一个...

**Comment by unnamed5719** [comment]
在64位系统下调用会出错...
`OSError: dlopen failed: "/data/data/com.termux/files/home/liba.so" is 32-bit instead of 64-bit`

**Comment by unnamed5719** [comment]
@BruceZhang1993 
好不容易弄到了32位的环境，这又是什么情况
`root@vultr:~# objdump -f liba.so 
liba.so:     file format elf32-i386
architecture: i386, flags 0x00000150:
HAS_SYMS, DYNAMIC, D_PAGED
start address 0x00000000
 
root@vultr:~# uname -a
Linux vultr.guest 4.10.0-041000-generic #201702191831 SMP Sun Feb 19 23:44:17 UTC 2017 i686 GNU/Linux
root@vultr:~# python3
Python 3.4.2 (default, Oct  8 2014, 13:14:40)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes import *
>>> a = CDLL('./liba.so')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/i386-linux-gnu/libc.so: invalid ELF header
>>>`
